import { SignInButton, SignOutButton, useUser } from "@clerk/clerk-react";
import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data } = api.plans.getAll.useQuery();

  const user = useUser();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-4xl font-bold text-white">
            Welcome to Fitness AI!
          </h1>
          {!user.isSignedIn ? <SignInButton /> : <SignOutButton />}
          {data?.map((item) => (
            <div key={item.id} className="whitespace-pre-line">
              {item.content}
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
